
import jsPDF from 'jspdf';
import { Campaign } from '@/hooks/useCampaigns';

export const exportDashboardToPDF = (
  campaigns: Campaign[],
  totalEngagement: number,
  filters?: {
    startDate?: string;
    endDate?: string;
    campaignIds?: string[];
  }
) => {
  const doc = new jsPDF();
  
  // Header
  doc.setFontSize(20);
  doc.text('Beyond Views Dashboard Report', 20, 30);
  
  // Date and filters info
  doc.setFontSize(12);
  const reportDate = new Date().toLocaleDateString();
  doc.text(`Generated on: ${reportDate}`, 20, 45);
  
  if (filters?.startDate || filters?.endDate) {
    const dateRange = `Date Range: ${filters.startDate || 'All'} - ${filters.endDate || 'All'}`;
    doc.text(dateRange, 20, 55);
  }
  
  // Summary metrics
  doc.setFontSize(16);
  doc.text('Summary Metrics', 20, 75);
  doc.setFontSize(12);
  
  const totalCampaigns = campaigns.length;
  const totalViews = campaigns.reduce((sum, c) => sum + c.total_views, 0);
  const avgEngagementRate = campaigns.length > 0 
    ? (campaigns.reduce((sum, c) => sum + c.engagement_rate, 0) / campaigns.length).toFixed(1)
    : 0;
  
  doc.text(`Total Campaigns: ${totalCampaigns}`, 20, 90);
  doc.text(`Total Views: ${totalViews.toLocaleString()}`, 20, 100);
  doc.text(`Total Engagement: ${totalEngagement.toLocaleString()}`, 20, 110);
  doc.text(`Average Engagement Rate: ${avgEngagementRate}%`, 20, 120);
  
  // Campaign details
  doc.setFontSize(16);
  doc.text('Campaign Details', 20, 140);
  doc.setFontSize(10);
  
  let yPosition = 155;
  campaigns.forEach((campaign, index) => {
    if (yPosition > 270) {
      doc.addPage();
      yPosition = 20;
    }
    
    doc.text(`${index + 1}. ${campaign.brand_name}`, 20, yPosition);
    doc.text(`Creator: ${campaign.creators?.name || 'N/A'}`, 30, yPosition + 10);
    doc.text(`Date: ${new Date(campaign.campaign_date).toLocaleDateString()}`, 30, yPosition + 20);
    doc.text(`Views: ${campaign.total_views.toLocaleString()}`, 30, yPosition + 30);
    doc.text(`Engagement: ${campaign.total_engagement.toLocaleString()}`, 30, yPosition + 40);
    doc.text(`Engagement Rate: ${campaign.engagement_rate}%`, 30, yPosition + 50);
    doc.text(`Deal Value: ${campaign.deal_value ? `$${campaign.deal_value.toLocaleString()}` : 'N/A'}`, 30, yPosition + 60);
    doc.text(`Status: ${campaign.status}`, 30, yPosition + 70);
    
    yPosition += 85;
  });
  
  // Save the PDF
  const filename = `dashboard-report-${reportDate.replace(/\//g, '-')}.pdf`;
  doc.save(filename);
};

export const exportCampaignToPDF = (campaign: Campaign) => {
  const doc = new jsPDF();
  
  // Header
  doc.setFontSize(20);
  doc.text('Campaign Report', 20, 30);
  
  // Campaign title
  doc.setFontSize(16);
  doc.text(campaign.brand_name, 20, 50);
  
  // Basic info
  doc.setFontSize(12);
  doc.text(`Creator: ${campaign.creators?.name || 'N/A'}`, 20, 70);
  doc.text(`Campaign Date: ${new Date(campaign.campaign_date).toLocaleDateString()}`, 20, 80);
  doc.text(`Status: ${campaign.status}`, 20, 90);
  doc.text(`Generated on: ${new Date().toLocaleDateString()}`, 20, 100);
  
  // Performance metrics
  doc.setFontSize(14);
  doc.text('Performance Metrics', 20, 120);
  doc.setFontSize(12);
  
  doc.text(`Total Views: ${campaign.total_views.toLocaleString()}`, 20, 140);
  doc.text(`Total Engagement: ${campaign.total_engagement.toLocaleString()}`, 20, 150);
  doc.text(`Engagement Rate: ${campaign.engagement_rate}%`, 20, 160);
  doc.text(`Deal Value: ${campaign.deal_value ? `$${campaign.deal_value.toLocaleString()}` : 'Not specified'}`, 20, 170);
  
  // Creator info
  if (campaign.creators?.platform_handles) {
    doc.setFontSize(14);
    doc.text('Creator Platform Handles', 20, 190);
    doc.setFontSize(12);
    
    let yPos = 205;
    Object.entries(campaign.creators.platform_handles).forEach(([platform, handle]) => {
      doc.text(`${platform}: ${handle}`, 20, yPos);
      yPos += 10;
    });
  }
  
  // Footer
  doc.setFontSize(10);
  doc.text('Generated by Beyond Views Analytics Platform', 20, 280);
  
  // Save the PDF
  const filename = `${campaign.brand_name.replace(/[^a-zA-Z0-9]/g, '-')}-campaign-report.pdf`;
  doc.save(filename);
};
